### ISSUE TITLE
Publish containers as public

### ISSUE THREAD

**Issue by maxirmx** [rnpgp/rnp-ci-containers#5]
Help is kindly requested for configuration of this repository
When I build containers in my personal repo with the same workflow images are published as 'public'
When I do it in rnp organization images are publushed as 'private' and they cannot be accessed from rnp workflows

We need either change image visibility to public or create an access token in rnp repo

**Comment by ronaldtse** [comment]
@maxirmx I've changed all the packages to public. Thanks.
